[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
contracts = "6k3zHEgbU4MwBjUKbLaDEwEo2bTNSWrn5wuWPYfyUjqH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
